# Generated by Django 5.0.6 on 2024-08-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="region",
                to="friender.region",
            ),
        ),
    ]
